sudo: required

before_install:
  - git clone https://github.com/yshtemp/ISD.git IDS

script:
  - travis_wait 30
  - chmod 775 ${TRAVIS_BUILD_DIR}/IDS/script.sh && cd ${TRAVIS_BUILD_DIR}/IDS/
  - ./script.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_CHM"
  file: "${TRAVIS_BUILD_DIR}/IDS/files/*.chm"
  on:
    repo: yshtemp/ISD
