sudo: required

script:
  - travis_wait 30
  - chmod 775 script.sh
  - ./script.sh
  
  deploy:
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_CHM"
  file: "${TRAVIS_BUILD_DIR}/files/*.chm"
  skip_cleanup: true
  on:
    tags: false
    branch: master
